In [1]:
#1. How to import pandas and check the version?

import pandas as pd
import numpy as np
print(pd.__version__)


1.4.3


In [2]:
#2. How to create a series from a list, numpy array and dict?
l=["p","a","1"]
K=pd.Series(l)
K

0    p
1    a
2    1
dtype: object

In [3]:
#3. How to convert the index of a series into a column of a dataframe?
df = K.to_frame().reset_index()
print(df.head())

   index  0
0      0  p
1      1  a
2      2  1


In [4]:
#4. How to combine many series to form a dataframe?
df = pd.DataFrame({'col1': K, 'col2': K})
print(df.head())

  col1 col2
0    p    p
1    a    a
2    1    1


In [5]:
#5. How to assign name to the series’ index?
K.name="name"

K.head()

0    p
1    a
2    1
Name: name, dtype: object

In [6]:
#6. How to get the items of series A not present in series B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [7]:
#7. How to get the items not common to both series A and series B?

# ser_u = pd.Series(np.union1d(ser1, ser2))  # union
# ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser3=ser1[~ser1.isin(ser2)]
ser4=ser2[~ser2.isin(ser1)]
ser5=pd.Series(np.union1d(ser3,ser4))
ser5

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [8]:
#8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

ser = pd.Series(np.random.normal(10, 5, 25))
print(ser)
np.percentile(ser, q=[0, 25, 50, 75, 100])

0     13.404697
1     14.322313
2     11.503880
3     12.379802
4      5.717911
5     11.440095
6      8.874998
7     14.976378
8     17.055364
9      8.223587
10    14.794246
11    10.812507
12    10.693211
13    12.329936
14     8.689697
15    20.957415
16     8.300510
17     9.771118
18     9.163451
19     7.136115
20     5.875803
21     8.839115
22    10.184883
23    12.240404
24    11.681630
dtype: float64


array([ 5.71791086,  8.8391151 , 10.81250743, 12.37980215, 20.95741462])

In [9]:
#9. How to get frequency counts of unique items of a series?
ser = pd.Series([1,1,2, 2, 3,3,3, 4, 5])
l=ser.unique()
l
l1=ser.value_counts()
print(l1)    

3    3
1    2
2    2
4    1
5    1
dtype: int64


In [10]:
#10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
ser = pd.Series([1,1,2, 2, 3,3,3, 4, 5])

ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

0        1
1        1
2    Other
3    Other
4        3
5        3
6        3
7    Other
8    Other
dtype: object

In [11]:
#11. How to bin a numeric series to 10 groups of equal size?
ser = pd.Series(np.random.random(5))
print(ser.head())

pd.qcut(ser, q=[0, .1, .2, .3, .4, .5, .6, .7,.8,.9,1] ,
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th','9th','10th'])

0    0.482844
1    0.390459
2    0.966928
3    0.674385
4    0.243467
dtype: float64


0     5th
1     3rd
2    10th
3     8th
4     1st
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

In [12]:
#12. How to convert a numpy array to a dataframe of given shape? (L1)
l=np.linspace(1,20,100)
l=pd.Series(l)
df= pd.DataFrame(l.values.reshape(20,5))
df

0          1          2          3          4
0    1.000000   1.191919   1.383838   1.575758   1.767677
1    1.959596   2.151515   2.343434   2.535354   2.727273
2    2.919192   3.111111   3.303030   3.494949   3.686869
3    3.878788   4.070707   4.262626   4.454545   4.646465
4    4.838384   5.030303   5.222222   5.414141   5.606061
5    5.797980   5.989899   6.181818   6.373737   6.565657
6    6.757576   6.949495   7.141414   7.333333   7.525253
7    7.717172   7.909091   8.101010   8.292929   8.484848
8    8.676768   8.868687   9.060606   9.252525   9.444444
9    9.636364   9.828283  10.020202  10.212121  10.404040
10  10.595960  10.787879  10.979798  11.171717  11.363636
11  11.555556  11.747475  11.939394  12.131313  12.323232
12  12.515152  12.707071  12.898990  13.090909  13.282828
13  13.474747  13.666667  13.858586  14.050505  14.242424
14  14.434343  14.626263  14.818182  15.010101  15.202020
15  15.393939  15.585859  15.777778  15.969697  16.161616
16  16.353535  16.545455  16.737374  16.929293  17.121212
17  17.313131  17.505051  17.696970  17.888889  18.080808
18  18.272727  18.464646  18.656566  18.848485  19.040404
19  19.232323  19.424242  19.616162  19.808081  20.000000

In [13]:
#13. How to find the positions of numbers that are multiples of 3 from a series?
ser = pd.Series([1,1,2, 2, 3,3,3, 4, 5])
for i in ser:
    if(i%3==0):
        print(ser[ser==i].index[0])



4
4
4


In [14]:
#14. How to extract items at given positions from a series
ser = pd.Series([1,1,2, 2, 3,3,3, 4, 5])
pos=[1,2,3,4]
ser.take(pos)

1    1
2    2
3    2
4    3
dtype: int64

In [15]:
#15. How to stack two series vertically and horizontally ?
ser = pd.Series([1,1,2, 2, 3,3,3, 4, 5])
df= pd.concat([ser,ser], axis=1)
df1= pd.concat([ser,ser], axis=0)

df

0  1
0  1  1
1  1  1
2  2  2
3  2  2
4  3  3
5  3  3
6  3  3
7  4  4
8  5  5

In [16]:
#16. How to get the positions of items of series A in another series B?
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
count=0
pos=[]
for i in ser2:
    #print(i)
    count=0
    while (count<len(ser1)):
        if(ser1[count]==i):
            pos.append(count)
        count=count+1
print(pos)




[5, 4, 0, 8]


In [17]:
#17. How to compute the mean squared error on a truth and predicted series?
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
count=0
total=0
sqr=0
while(count< len(truth)):
    sqr=truth[count]-pred[count]
    total=total+sqr*sqr
    count=count+1
print(total)   

3.423963717816888


In [18]:
#18. How to convert the first character of each element in a series to uppercase?
lst=[]
ser = pd.Series(['how', 'to', 'kick', 'ball?'])
for i in ser:
    lst.append(i.title())
ser1=pd.Series(lst)
print(ser1)

0      How
1       To
2     Kick
3    Ball?
dtype: object


In [19]:
#19. How to calculate the number of characters in each word in a series?
ser = pd.Series(['how', 'to', 'kick', 'ball?'])
lst=[]
for i in ser:
    lst.append(len(i))
ser2=pd.Series(lst)
print(ser2)

0    3
1    2
2    4
3    5
dtype: int64


In [20]:
#20. How to compute difference of differences between consequtive numbers of a series?

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
print(ser.diff().diff().tolist())

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [21]:
#21. How to convert a series of date-strings to a timeseries?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [22]:
#22. How to get the day of month, week number, day of year and day of week from a series of date strings?

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
# Solution
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.isocalendar().week.tolist())

# day of year
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())

# day of week
print("Day of week: ", ser_ts.dt.day_name().tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


In [23]:
#23. How to convert year-month string to dates corresponding to the 4th day of the month?

ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [24]:
#24. How to filter words that contain atleast 2 vowels from a series?
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
count=0
for i in ser:
    count=0
    for k in i:
        if(k in 'aeiouAEIOU'):
            count=count+1
    if(count >=2):
        print(i)

Apple
Orange
Money


In [25]:
#25. How to filter valid emails from a series?

emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
import re
emails.str.findall(pattern, flags=re.IGNORECASE).tolist()

[[], ['rameses@egypt.com'], ['matt@t.co'], ['narendra@modi.com']]

In [26]:
#26. How to get the mean of a series grouped by another series?
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
# mydict={i:0 for i in fruit}
# print(mydict)
# count=0
# l=0
# while(count<len(fruit)):
#     #print(fruit[count])
#     l=str(fruit[count])
#     mydict[l]=mydict[l]+weights[count]
#     count=count+1

weights.groupby(fruit).mean()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'carrot', 'carrot', 'carrot', 'carrot', 'carrot', 'apple', 'carrot', 'banana', 'banana']


apple     7.000000
banana    6.666667
carrot    4.666667
dtype: float64

In [27]:
#27. How to compute the euclidean distance between two series?
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
(np.sum((p-q)**2))**.5

18.16590212458495

In [28]:
# 28. How to find all the local maxima (or peaks) in a numeric series?
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
count=0
while(count<len(ser)):
    
    if(count==len(ser)-1):
        if(ser[count]>ser[count-1]):
            print(ser[count])
        break
        
    if(ser[count]<ser[count+1]):
        pass
    else:
        print(ser[count])
    count=count+1


10
10
7


In [29]:
#29. How to replace missing spaces in a string with the least frequent character?

my_str = 'dbc deb abed gade'
all_freq = {}
  
for i in my_str:
    if i in all_freq:
        all_freq[i] += 1
    else:
        all_freq[i] = 1
temp = min(all_freq.values())
res = [key for key in all_freq if all_freq[key] == temp]

my_str.replace(' ',res[0])

'dbccdebcabedcgade'

In [30]:
#30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    1
2000-01-08    2
2000-01-15    7
2000-01-22    8
2000-01-29    6
2000-02-05    9
2000-02-12    5
2000-02-19    3
2000-02-26    4
2000-03-04    5
Freq: W-SAT, dtype: int32

In [31]:
#31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

ser.resample('D').ffill()  # fill with previous value

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [32]:
#32.How to get the last n rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

rowsums = df.apply(np.sum, axis=1)

# last two rows with row sum greater than 100
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]
last_two_rows

0   1   2   3
4   10  35  37  34
10  17  31  22  31

In [33]:
#33.How to format or suppress scientific notations in a pandas dataframe?
df = pd.DataFrame(np.random.random(10)**10, columns=['random'])
df.round(3)



random
0   0.171
1   0.000
2   0.000
3   0.015
4   0.000
5   0.361
6   0.002
7   0.000
8   0.372
9   0.000

In [34]:
#34. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    2
2000-01-08    2
2000-01-15    4
2000-01-22    7
2000-01-29    7
2000-02-05    7
2000-02-12    7
2000-02-19    9
2000-02-26    3
2000-03-04    6
Freq: W-SAT, dtype: int32

In [35]:
#35. How to create a dataframe with rows as strides from a given series?

L = pd.Series(range(15))
l=list(L)
l=np.array(l)
l=l.reshape(3,5)
df=pd.DataFrame(l)
print(df)

print("       ")
print(l)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
       
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [36]:
#36. How to import only specified columns from a csv file?

df = pd.read_csv('accidents_2017.csv', usecols=['Weekday', 'Vehicles involved'])
print(df.head())

    Weekday  Vehicles involved
0    Friday                  2
1    Friday                  2
2    Friday                  2
3    Friday                  2
4  Thursday                  3


In [37]:
#37. How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? 
# Also get the array and list equivalent.

df = pd.read_csv('accidents_2017.csv')
print(df.shape)
print(df.dtypes)
#print(df.get_dtype_counts())
#print(df.dtypes.value_counts())
#df_stats = df.describe()                                    
df_arr = df.values
df_list = df.values.tolist()
print(df_arr)


(10339, 15)
Id                    object
District Name         object
Neighborhood Name     object
Street                object
Weekday               object
Month                 object
Day                    int64
Hour                   int64
Part of the day       object
Mild injuries          int64
Serious injuries       int64
Victims                int64
Vehicles involved      int64
Longitude            float64
Latitude             float64
dtype: object
[['2017S008429    ' 'Unknown' 'Unknown' ... 2 2.12562442 41.34004482]
 ['2017S007316    ' 'Unknown' 'Unknown' ... 2 2.12045245 41.33942606]
 ['2017S010210    ' 'Unknown' 'Unknown' ... 2 2.1673561 41.3608855]
 ...
 ['2017S010718    ' 'Sant Andreu' 'el Bon Pastor' ... 2 2.205607
  41.443894]
 ['2017S006145    ' 'Sant Andreu' 'el Bon Pastor' ... 2 2.205118
  41.444824]
 ['2017S000178    ' 'Sant Andreu' 'el Bon Pastor' ... 1 2.200956
  41.437125]]


In [38]:
#38. How to extract the row and column number of a particular cell with given criterion?

df = pd.read_csv('accidents_2017.csv')

df.loc[df.Hour == np.max(df.Hour), ['Weekday', 'Vehicles involved']]

Weekday  Vehicles involved
37     Wednesday                  1
53     Wednesday                  5
57       Tuesday                  2
133       Friday                  1
176       Monday                  2
...          ...                ...
10091   Saturday                  2
10140   Thursday                  2
10141     Monday                  1
10248     Friday                  2
10260     Monday                  2

[207 rows x 2 columns]

In [39]:
#39. How to rename a specific columns in a dataframe?

df = pd.read_csv('accidents_2017.csv')
print(df.columns)

print('\n \n')
df.columns = df.columns.map(lambda x: x.replace(' ', '_'))
print(df.columns)

Index(['Id', 'District Name', 'Neighborhood Name', 'Street', 'Weekday',
       'Month', 'Day', 'Hour', 'Part of the day', 'Mild injuries',
       'Serious injuries', 'Victims', 'Vehicles involved', 'Longitude',
       'Latitude'],
      dtype='object')

 

Index(['Id', 'District_Name', 'Neighborhood_Name', 'Street', 'Weekday',
       'Month', 'Day', 'Hour', 'Part_of_the_day', 'Mild_injuries',
       'Serious_injuries', 'Victims', 'Vehicles_involved', 'Longitude',
       'Latitude'],
      dtype='object')


In [40]:
#40. How to check if a dataframe has any missing values?
df = pd.read_csv('accidents_2017.csv')
df.isnull().values.any()

False

In [41]:
#41. How to count the number of missing values in each column?
df = pd.read_csv('accidents_2017.csv')
n_missings_each_col = df.apply(lambda x: x.isnull().sum())
n_missings_each_col.argmax()

0

In [42]:
#42. How to replace missing values of multiple numeric columns with the mean?
df = pd.read_csv('accidents_2017.csv')
df_out = df[['Mild injuries', 'Serious injuries']] = df[['Mild injuries', 'Serious injuries']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Mild injuries  Serious injuries
0              2                 0
1              2                 0
2              5                 0
3              1                 0
4              1                 0


In [43]:
#43. How to use apply function on existing columns with global variables as additional arguments?
df = pd.read_csv('accidents_2017.csv')
d = {'Mild injuries': np.nanmean, 'Serious injuries': np.nanmedian}
df[['Mild injuries', 'Serious injuries']] = df[['Mild injuries', 'Serious injuries']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))

In [44]:
#44. How to select a specific column from a dataframe as a dataframe instead of a series?
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

pandas.core.frame.DataFrame

In [45]:
#45. How to change the order of columns of a dataframe?
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df[list('cbade')]

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [46]:
#46. How to set the number of rows and columns displayed in the output?
df = pd.read_csv('accidents_2017.csv')
pd.set_option('display.max_columns', 1)
pd.set_option('display.max_rows', 10)
df

Id  ...
0      2017S008429      ...
1      2017S007316      ...
2      2017S010210      ...
3      2017S006364      ...
4      2017S004615      ...
...                ...  ...
10334  2017S003667      ...
10335  2017S001896      ...
10336  2017S010718      ...
10337  2017S006145      ...
10338  2017S000178      ...

[10339 rows x 15 columns]

In [47]:
#47. How to format or suppress scientific notations in a pandas dataframe?
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df.round(4)

random
0  0.0000
1  0.0026
2  0.0000
3  0.0000

In [48]:
#48. How to format all the values in a dataframe as percentages?
df = pd.DataFrame(np.random.random(4), columns=['random'])
print(df)
out = df.style.format({
    'random': '{0:.2%}'.format,
})

out

     random
0  0.557102
1  0.581703
2  0.474687
3  0.024537


In [49]:
#49. How to filter every nth row in a dataframe?
df = pd.read_csv('accidents_2017.csv')
print(df.iloc[::100, :][['Hour']])

       Hour
0         8
100      16
200      14
300       8
400      15
...     ...
9900     18
10000     8
10100    17
10200     5
10300     9

[104 rows x 1 columns]


In [50]:
#50. How to get the row number of the nth largest value in a column?
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
print(df)
n = 5
df['a'].argsort()[::-1][n]

    a  ...
0  11  ...
1   7  ...
2   8  ...
3   8  ...
4  22  ...
5  14  ...
6   7  ...
7   6  ...
8  28  ...
9  22  ...

[10 rows x 3 columns]


0